// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgADmsxPAVij2ngey3YkYUwxqg3EymyvA',
    appId: '1:593068032217:web:c45816e947ee09cf20fec8',
    messagingSenderId: '593068032217',
    projectId: 'chat-app-267bb',
    authDomain: 'chat-app-267bb.firebaseapp.com',
    storageBucket: 'chat-app-267bb.appspot.com',
    measurementId: 'G-YBNMVC7GY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_n5HjProQqIvsJVIKd0v2kQBtBq2h9vU',
    appId: '1:593068032217:android:ea504e9fdcb8aaed20fec8',
    messagingSenderId: '593068032217',
    projectId: 'chat-app-267bb',
    storageBucket: 'chat-app-267bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ4anQnItpNUtXpw7X7t5c7fJuzouJVMo',
    appId: '1:593068032217:ios:e7f4c7ba456f956520fec8',
    messagingSenderId: '593068032217',
    projectId: 'chat-app-267bb',
    storageBucket: 'chat-app-267bb.appspot.com',
    iosClientId: '593068032217-034q1naguonvqvkog2afmc6s6ml9jmpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
